export interface RunewordEntry {
  name: string;
  base: string;
  items: string[];
}

export const runewords: RunewordEntry[] = [
  {
    name: "HOTO (Updated)",
    base: "Now works in all weapons",
    items: [],
  },
  {
    name: "Insight (Updated)",
    base: "Now works in bows and swords (in addition to existing bases)",
    items: [],
  },
  {
    name: "Infinity (Updated)",
    base: "Can also be made in Amazon spears",
    items: [],
  },
  {
    name: "Wings Of Hope",
    base: "3 Socket Weapon - Hel + Io + Tir / Hel + Io + Nef",
    items: [
      "Level 3 Holy Vigor Aura When Equipped / Level 3 Holy Freeze Aura When Equipped",
      "1 To all Skills",
      "20% Faster Cast Rate",
      "+20% To all Resistances",
      "+50 To Mana",
      "2 To Mana After Each Kill",
      "+10 To Vitality",
      "+30% Magic Find",
      "Requirements -20%",
    ],
  },
  {
    name: "Knowledge",
    base: "4 Socket Armor - Shael + Um + Shael + Vex",
    items: [
      "+1 To All Skills",
      "+40 Faster Hit Recovery",
      "20% Increased Chance Of Blocking",
      "150-200% Enhanced Defense (varies)",
      "Replenish Life +10",
      "Regenerate Mana 10%",
      "+5% To Maximum Fire Resist",
      "+30-40 All Resistances (varies)",
      "+5-15% To Experience Gained (varies)",
    ],
  },
  {
    name: "Little Hydra",
    base: "4 Socket Bow - Hel + Shael + Amn + Vex",
    items: [
      "20% IAS",
      "200-300% Enhanced Damage",
      "Max Damage/lvl - 2*lvl",
      "40-60% Attack Rating",
      "Life/mana steal 7%",
      "Requirements -20%",
      "Half freeze duration",
    ],
  },
  {
    name: "Nightfall",
    base: "2 Socket Helm - Um + Um",
    items: [
      "+30% To all Resistances",
      "+50-100% Enhanced Damage (varies)",
      "+15-30% Increased Attack Speed (varies)",
      "+50-100 Defense (varies)",
      "+6-12% Life Stolen Per Hit",
      "+6-12% Mana Stolen Per Hit",
    ],
  },
  {
    name: "Flickering Flame",
    base: "3 Socket Helm - Nef + Pul + Vex",
    items: [
      "Level 4-8 Resist Fire Aura When Equipped",
      "+3 To Fire Skills",
      "-10-15% to Enemy Fire Resist",
      "+30% Enhanced Defense",
      "+30 Defense vs. Missile",
      "+50-75 To Mana",
      "Half Freeze Duration",
      "+5% To Maximum Fire Resist",
      "Poison Length Reduced by 50%",
    ],
  },
  {
    name: "Bulwark",
    base: "3 Socket Helm - Shael + Io + Sol",
    items: [
      "+20% Faster Hit Recovery",
      "+4-6% Life stolen per hit",
      "+75-100% Enhanced Defense",
      "+10 to Vitality",
      "Increase Maximum Life 5%",
      "Replenish Life +30",
      "Damage Reduced by 7",
      "Physical Damage Received Reduced by 10-15%",
    ],
  },
  {
    name: "Ground",
    base: "3 Socket Helm - Shael + Io + Ort",
    items: [
      "+20% Faster Hit Recovery",
      "+75-100% Enhanced Defense",
      "+10 to Vitality",
      "Increase Maximum Life 5%",
      "Lightning Resist +40-60%",
      "Lightning Absorb +10-15%",
    ],
  },
  {
    name: "Cure",
    base: "3 Socket Helm - Shael + Io + Tal",
    items: [
      "+20% Faster Hit Recovery",
      "+10 to Vitality",
      "Poison Resist +30%",
      "Level 1 Cleansing Aura when Equipped",
      "+75-100% Enhanced Defense",
      "Increase Maximum Life 5%",
      "Poison Resist +10-30% (+40-60% total)",
      "Poison Length Reduced by 50%",
    ],
  },
  {
    name: "Piety",
    base: "2 Socket Helms - Lum + Ist",
    items: [
      "+2 To All Skill Levels",
      "+10 To Energy",
      "+60 To Life",
      "+30-50% Magic Find (Varies)",
      "+5-20% All resistances (Varies)",
      "+30% Faster Hit Recovery",
      "Reduced Vendor Prices 15-30% (Varies)",
    ],
  },
  {
    name: "Tempest",
    base: "4 Socket Armors - Ist + Ist + Ist + Ist",
    items: [
      "1 To All Skills",
      "+20% Faster Cast Rate",
      "+20 All Resistances",
      "120% Better Chance Of Getting Magic Items",
      "Better Chance Of Getting Magic Items based on character level",
    ],
  },
  {
    name: "Whisper (Barbarian)",
    base: "3 Socket Barbarian Helmets - Um + Lo + Shael",
    items: [
      "+2 Barbarian Skills",
      "+20% Faster Hit Recovery",
      "+30-40 Damage (varies)",
      "+350-450 Attack Rating (varies)",
      "+5% to Maximum Lighting Resist",
      "+35% All Resistances",
    ],
  },
  {
    name: "Vengeance",
    base: "3 Socket Shields - Um + Shael + Ist",
    items: [
      "+1 to All Skills",
      "+20% Faster Cast Rate",
      "+20% Faster Block Rate",
      "30% Increased Chance Of Blocking",
      "+22-27 All Resistances (varies)",
      "Cannot Be Frozen",
      "30-35% Better Chance of Getting Magic Items (varies)",
    ],
  },
  {
    name: "Trust",
    base: "4 Socket Armor - Shael + Um + Zod + Ber",
    items: [
      "Indestructible",
      "+2 To All Skills",
      "+20% Faster Hit Recovery",
      "+250-300% Enhanced Damage (varies)",
      "+80-100% Enhanced Defense (varies)",
      "+10 To All Attributes",
      "All Resistances +15-30 (varies)",
      "Damage Reduced by 8%",
    ],
  },
  {
    name: "Truth",
    base: "4 Socket Shields - Ber + Pul + Ber + Um",
    items: [
      "Level 8-12 Redemption Aura When Equipped (varies)",
      "+2-3 To All Skills (varies)",
      "+30% Faster Block Rate",
      "+30% Increased Chance of Blocking",
      "+30% Enhanced Defense",
      "+30 To Strength",
      "All Resistances +30-45",
      "Damage Reduced By 16%",
      "Cannot Be Frozen",
    ],
  },
  {
    name: "Unbending Will",
    base: "4 Socket Shields - Vex + Um + Lo + Jah",
    items: [
      "Indestructible",
      "+25% Increased Attack Speed",
      "+35% Faster Block Rate",
      "35% Increased Chance of Blocking",
      "+2-247 Defense (2.5 Defense Per Character Level)",
      "+40 to Strength",
      "+50 Life",
      "+5% to Maximum Lightning Resist",
      "+5% to Maximum Fire Resist",
      "+22% To All Resistances",
      "Damage Reduced by 25-35% (varies)",
    ],
  },
  {
    name: "Voice (Wands/Orbs)",
    base: "2 Socket Wands/Orbs - Jah + Sur",
    items: [
      "+2-3 to All Skills (varies)",
      "+50% Faster Cast Rate",
      "Ignore Target Defense",
      "Hit Blinds Target",
      "+10 all attributes",
      "Increase max mana 10%",
      "Regenerate mana 10%",
      "All Resistances +35-50 (varies)",
    ],
  },
  {
    name: "Voice (Barb/Druid Helms)",
    base: "2 Socket Druid/Barbarian Helms - Jah + Sur",
    items: [
      "+2-3 to All Skills (varies)",
      "+50% Faster Cast Rate",
      "+10 all attributes",
      "Increase Maximum Life 5%",
      "Increase Maximum Mana 15%",
      "Regenerate mana 10%",
      "All Resistances +35-50 (varies)",
    ],
  },
  {
    name: "Void",
    base: "6 Socket Weapons - Zod + Shael + Mal + Ber + Eth + Ber",
    items: [
      "Indestructible",
      "+45-60% Increased Attack Speed",
      "400% Enhanced Damage",
      "-25% To Target Defense",
      "+30%-50% Bonus to Attack Rating",
      "+5%-8% Mana Stolen per Hit",
      "40% Chance Of Crushing Blow",
      "Prevent Monsters Heal",
      "+20 Strength",
      "+20 Dexterity",
    ],
  },
  {
    name: "Plague (Shield)",
    base: "4 Socket Shields - Shael + Um + Um + Ber",
    items: [
      "+2 To Amazon Skills",
      "+1-3 To Plague Javelin",
      "+1-3 To Poison Javelin",
      "+25% Faster Cast Rate",
      "+25% Increased Attack Speed",
      "All Resistances +30",
      "+8% Damage reduced",
      "+20% Faster Block Rate",
    ],
  },
  {
    name: "Plague (Weapon)",
    base: "3 Socket Sword, Dagger, Assassin Weapon - Cham + Shael + Um",
    items: [
      "20% Chance to cast level 12 Lower Resist when struck",
      "25% Chance to cast level 15 Poison Nova on striking",
      "Level 13-17 Cleansing Aura When Equipped (varies)",
      "+1-2 All Skills",
      "+20% Increased Attack Speed",
      "+220-320% Enhanced Damage (varies)",
      "-23% To Enemy Poison Resistance",
      "0.3% (0-29.7) Deadly Strike (Based on Character Level)",
      "+25% Chance of Open Wounds",
      "Freezes Target +3",
    ],
  },
  {
    name: "Hand Of Midas",
    base: "6 Socket Sword - Lem x6",
    items: [
      "+20% Faster Cast Rate",
      "+20% Faster Run Walk",
      "+450% Extra Gold From Monsters",
      "+2-173% Extra Gold From Monsters (1.74% per Level)",
      "+40-50 To Mana (varies)",
      "Prevent Monster Heal",
      "+(1) To Find Item",
    ],
  },
  {
    name: "Tyrael's Gloria",
    base: "2 Socket Diadem - Zod + Jah",
    items: [
      "+2-3 To All Skills (varies)",
      "+20% Faster Cast Rate",
      "+150 Defense",
      "+5-10 To All Attributes (varies)",
      "Increase Maximum Life 5%",
      "All Resistances +15-30 (Varies)",
      "100% Better Chance Of Getting Magic Items",
    ],
  },
  {
    name: "Loyalty",
    base: "6 Socket Swords - Fal + Dol + Vex + Io + Lum + Mal",
    items: [
      "+2-3 To Barb Skills Levels",
      "+2-4 To Warcry",
      "+20-30% Faster Cast Rate",
      "+20-30% Faster Hit Recovery",
      "+10 To Strength",
      "+10 To Vitality",
      "+10 To Energy",
      "+7% Mana Stolen Per Hit",
      "Hit Causes Monsters To Flee 25%",
      "Prevent Monster Heal",
    ],
  },
  {
    name: "Hustle (Weapon)",
    base: "3 Socket Weapons - Shael + Ko + Eld",
    items: [
      "5% Chance to cast level 1 Burst of Speed on striking",
      "Level 1 Fanaticism Aura",
      "+30% Increased Attack Speed",
      "+180-200% Enhanced Damage",
      "+75% Damage to Undead",
      "+50 to Attack Rating against Undead",
      "+10 to Dexterity",
    ],
  },
  {
    name: "Hustle (Armor)",
    base: "3 Socket Armor - Shael + Ko + Eld",
    items: [
      "+65% Faster Run/Walk",
      "+40% Increased Attack Speed",
      "+20% Faster Hit Recovery",
      "+6 to Evade",
      "+10 to Dexterity",
      "50% Slower Stamina Drain",
      "+All Resistances +10",
    ],
  },
  {
    name: "Blood",
    base: "3 Socket Helm - Ko + Gul + Um",
    items: [
      "+1 to Traps [Assassin Only]",
      "+1 to Assassin Skills",
      "+15% Increased Attack Speed",
      "+1 to Lightning Sentry [Assassin Only]",
      "+7 to Strength",
      "+10 to Dexterity",
      "+45 to Life",
      "+5% to Maximum Poison Resist",
      "All Resistances +15",
    ],
  },
  {
    name: "Terror (Paladin)",
    base: "4 Socket Paladin Shields - Eth + Tal + Eld + Amn",
    items: [
      "+20 All Resistances",
      "+50-80 Life (varies)",
      "+50 Defense Vs. Missile",
      "20% Increased Chance of Blocking",
      "40% Faster Block Rate",
      "25% Faster Cast Rate",
      "+1 Paladin Skill Levels",
    ],
  },
  {
    name: "Cataclysm",
    base: "4 Socket Armor - Zod + Ber + Shael + Ber",
    items: [
      "Indestructible",
      "+20% Faster Hit Recovery",
      "+330-350% Enhanced Damage (varies)",
      "+250 to Attack Rating",
      "15% Crushing Blow",
      "15% Deadly Strike",
      "+250% Enhanced Defense",
      "+15-25 to All Attributes",
      "+Life (based on character level)",
      "Damage Reduced by 16%",
    ],
  },
  {
    name: "Seraphim",
    base: "3 Socket Helms (Diadem type) - Jah + Shael + Ber",
    items: [
      "+2-3 to All Skills (varies)",
      "+20-25% Faster Cast Rate (varies)",
      "+20% Faster Hit Recovery",
      "+20 to All Attributes",
      "Increase Maximum Life 5%",
      "All Resistances +15-25 (varies)",
      "Damage Reduced by 10-20% (varies)",
    ],
  },
  {
    name: "Desolator",
    base: "6 Socket Swords/Axes - Shael + Gul + Shael + Ber + Eth + Lo",
    items: [
      "+1 to All Skills",
      "+40% Increased Attack Speed",
      "Damage +350-400 (varies)",
      "-25% Target Defense",
      "20% Bonus to Attack Rating",
      "+250 to Attack Rating",
      "20% Chance of Crushing Blow",
      "40% Deadly Strike",
      "All Resistances +30",
    ],
  },
];
